### PR TITLE
Fix w.r.t. coq/coq#11764.

### PR DESCRIPTION
**Pull request by ppedrot**
Do not merge yet.

### CODE REVIEW

**Comment by ppedrot** [comment]
Please merge.

**Comment by JasonGross** [comment]
Will merge once the CI passes (I just restarted it)

**Comment by ejgallego** [comment]
> Will merge once the CI passes (I just restarted it)

The CI somehow picked the wrong Coq version.

**Comment by JasonGross** [comment]
> The CI somehow picked the wrong Coq version.

It uses the latest version from my launchpad package.  It was lagging behind.  I just updated that package, and restarted the CI, hopefully it should succeed this time.

**Comment by ejgallego** [comment]
Thanks @JasonGross !

**Pull request merged**
