### PR TITLE
[coq] Adapt to coq/coq#12372

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
@JasonGross , does this need some tweak to recognize 8.13?

**Comment by JasonGross** [comment]
Indeed, there needs to be a change to
https://github.com/mit-plv/rewriter/blob/1e47fca6eb33b149119025be063c935f0393b76a/Makefile.local.common#L26-L34

**Comment by JasonGross** [comment]
Do you want me to make the change, or will you make it in this PR?

**Comment by ejgallego** [comment]
Thanks @JasonGross , I had indeed done the change but forgot to push, should be working (TM)

**Comment by JasonGross** [comment]
Gives the error
```
File "src/Rewriter/Util/plugins/definition_by_tactic.ml", line 4, characters 14-32:
Error: Unbound module Declare.CInfo
Hint: Did you mean Info?
```
I take it the Coq PR needs to be merged first?

**Comment by ejgallego** [comment]
Yup, I used draft status to indicate that

**Comment by SkySkimmer** [comment]
Please merge now.

**Pull request merged**
