### PR TITLE
Adapt to coq/coq#17475 (Ltac2 externals can have arity 0)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by JasonGross** [comment]
I will set this one up to auto-merge as well, so that there's no two-day delay like last time.  Just force-push / rebase (or `git commit --amend --reset-author` and force push) after the merge happens into Coq master, and this should auto-merge once CI passes

**Comment by ppedrot** [comment]
@SkySkimmer you'll have to force-push, I think I don't have the rights on this repo.

**Comment by SkySkimmer** [comment]
>I will set this one up to auto-merge as well, so that there's no two-day delay like last time. Just force-push / rebase (or git commit --amend --reset-author and force push) after the merge happens into Coq master and the docker dev image is updated, and this should auto-merge once CI passes

@JasonGross that doesn't work, see the message github left:

> auto-merge was automatically disabled May 2, 2023 10:02
Head branch was pushed to by a user without write access

**Comment by SkySkimmer** [comment]
Please merge now

**Pull request merged**
