### PR TITLE
[coq] Adapt to coq/coq#11731

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Merge now

**Comment by JasonGross** [comment]
I have triggered a build of my Debian package at https://code.launchpad.net/~jgross-h/+recipe/coq-master-daily-coqide-no , will restart the CI here once that finishes, and will merge once the CI passes.

**Comment by JasonGross** [comment]
Merged, thanks for the PR!

**Comment by ejgallego** [comment]
Thanks @JasonGross

**Pull request merged**
